CC      ?= gcc
CFLAGS  ?= -g -Wall -std=c99

all : listar untar mktar untarCorr untarAmenah mktarCorr

listar : listar.c tarutils.o

untar  : untar.c tarutils.o

mktar : mktar.c tarutils.o

untarCorr : untarCorr.c tarutils.o

untarAmenah : untarAmenah.c tarutils.o

mktarCorr : mktarCorr.c tarutils.o
